title = "Custom Gitleaks Rules"

[[rules]]
id = "terraform-secrets"
description = "Detect Terraform Secrets"

regex = '''(?i)(password|secret|client_secret|token|access_key)\s*=\s*["']?[^"'\s]+["']?'''

tags = ["terraform", "security"]

[[allowlists]]
description = "Temporary test password"
regexes = [
  '''Password123!'''
]

[[allowlists]]
description = "Ignore Git internal files"
paths = [
  '''^\.git/'''
]